version: '3.8'

services:
  site:
    build:
      context: ./
      dockerfile: ../../build/docker/Dockerfile.dev
    container_name: nvnc.site
    env_file:
      - .env
    volumes:
      - ../../:/app
    ports:
      - ${DEV_SERVER_PORT}:3000
